In [1]:
import requests
import re
import numpy as np
from bs4 import BeautifulSoup
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [28]:
TITLES = []
RATING = []
AREA = []
DISHES = []
APPROX = []
DISC = []

city = ['ahmedabad', 'mumbai', 'pune', 'bengaluru']
for c in city:
    for i in range(1,16):
        url = f"https://www.eazydiner.com/restaurants?location={c}&page={i}"
        requests.get(url)
        page = requests.get(url)
        soup = BeautifulSoup(page.text)
        title = soup.find_all('a', class_='ellipsis listing_res_name__uVIN8')
        for i in title:
            TITLES.append(i.text)
        rating = soup.find_all('tspan')
        for i in rating:
            j = i.text
            if j != '%':
                if j:
                    RATING.append(j)
                else:
                    RATING.append(np.nan)
        area = soup.find_all('div', class_='font-12 ellipsis flex listing_res_address__LuVOm')
        for i in area:
            AREA.append(i.text)
        dishes = soup.find_all('div', class_='flex align-v-center ellipsis listing_multi_cuisines__zLLXK')
        for i in dishes:
            if i:
                DISHES.append(i.text)
            else:
                DISHES.append(np.nan)
        txt = []
        approx = soup.find_all('div', class_='flex align-v-center')
        for i in approx:
            txt.append(i.text)
        for i in txt:
            if re.match("₹ +\d+ [A-Za-z].+", i):
                APPROX.append(i)
            else:
                pass
        discount = soup.find_all('div', class_='ellipsis listing_offer_text__LXKw1')
        for i in discount:
            DISC.append(i.text)

print(len(TITLES))
print(len(RATING))
print(len(AREA))
print(len(DISHES))
print(len(APPROX))
print(len(DISC))

540
540
540
540
540
540

In [29]:
data={
    'NAME': TITLES,
    'RATING': RATING,
    'AREA': AREA,
    'DISHES': DISHES,
    'APPROX': APPROX,
    'DISC': DISC
}
df = pd.DataFrame(data)
df

,NAME,RATING,AREA,DISHES,APPROX,DISC
0,Table Tales,4.8,"Bodakdev, West Ahmedabad",Multicuisine,₹ 1500 for two approx.,10% Off + 25% Off
1,Banjara- Gourmet Dining,4.5,"Bodakdev, West Ahmedabad",Multicuisine,₹ 1700 for two approx.,20% Off + 25% Off
2,Laurel - An Essence Of Flavors,5.0,"Ambli, Ahmedabad",Multicuisine,₹ 1800 for two approx.,20% Off + 25% Off
3,The Chocolate Room,5.0,"Prahlad Nagar, West Ahmedabad | View All(19) ...",Bakery,₹ 500 for two approx.,35% Off + 25% Off
4,Essence,4.5,"Crowne Plaza, Ahmedabad","Indian, North Indian",₹ 2000 for two approx.,50% Off + 25% Off
...,...,...,...,...,...,...
535,Blah Bla (Indigo XP),3.9,"Koramangala, South Bengaluru",Multicuisine,₹ 2000 for two approx.,40% Off + 25% Off
536,Scottish Pub,4.8,"St. Marks Road, Central Bengaluru",Multicuisine,₹ 2000 for two approx.,10% Off + 25% Off
537,"Salt - Pan Indian Restaurant, Bar & Grill",4.2,"UB City, Central Bengaluru | View All(5) Outlets","Indian, Cocktail Menu",₹ 2000 for two approx.,25% Off :Payeazy
538,Frenzy Pub,4.5,"Marathahalli, East Bengaluru",Multicuisine,₹ 2000 for two approx.,40% Off + 25% Off
539,Howl’n Pub,4.3,"Church Street, Central Bengaluru",Multicuisine,₹ 1400 for two approx.,10% Off + 25% Off

In [30]:
df.to_csv('restaurant_data.csv', index=False)